[2022-12-13T16:30:53.203+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bus_pos_etl.etl_bus_loc manual__2022-12-13T16:30:51.280332+00:00 [queued]>
[2022-12-13T16:30:53.213+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bus_pos_etl.etl_bus_loc manual__2022-12-13T16:30:51.280332+00:00 [queued]>
[2022-12-13T16:30:53.213+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T16:30:53.214+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-13T16:30:53.214+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T16:30:53.233+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): etl_bus_loc> on 2022-12-13 16:30:51.280332+00:00
[2022-12-13T16:30:53.241+0000] {standard_task_runner.py:55} INFO - Started process 1021 to run task
[2022-12-13T16:30:53.244+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bus_pos_etl', 'etl_bus_loc', 'manual__2022-12-13T16:30:51.280332+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/test_noe_bash.py', '--cfg-path', '/tmp/tmpwhqh727y']
[2022-12-13T16:30:53.246+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask etl_bus_loc
[2022-12-13T16:30:53.312+0000] {task_command.py:389} INFO - Running <TaskInstance: bus_pos_etl.etl_bus_loc manual__2022-12-13T16:30:51.280332+00:00 [running]> on host ff6f332d28b5
[2022-12-13T16:30:53.412+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=noe
AIRFLOW_CTX_DAG_ID=bus_pos_etl
AIRFLOW_CTX_TASK_ID=etl_bus_loc
AIRFLOW_CTX_EXECUTION_DATE=2022-12-13T16:30:51.280332+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-13T16:30:51.280332+00:00
[2022-12-13T16:30:53.415+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-13T16:30:53.418+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl/etl.py']
[2022-12-13T16:30:53.458+0000] {subprocess.py:86} INFO - Output:
[2022-12-13T16:30:54.729+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-13T16:30:54.730+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/etl/etl.py", line 9, in <module>
[2022-12-13T16:30:54.731+0000] {subprocess.py:93} INFO -     storage_client = storage.Client.from_service_account_json('/opt/***/dags/etl/etl.py/midyear-cursor-371415-a5bbee084fb8.json')
[2022-12-13T16:30:54.731+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
[2022-12-13T16:30:54.731+0000] {subprocess.py:93} INFO -     with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
[2022-12-13T16:30:54.731+0000] {subprocess.py:93} INFO - NotADirectoryError: [Errno 20] Not a directory: '/opt/***/dags/etl/etl.py/midyear-cursor-371415-a5bbee084fb8.json'
[2022-12-13T16:30:54.940+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-13T16:30:54.956+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-13T16:30:54.969+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bus_pos_etl, task_id=etl_bus_loc, execution_date=20221213T163051, start_date=20221213T163053, end_date=20221213T163054
[2022-12-13T16:30:54.986+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task etl_bus_loc (Bash command failed. The command returned a non-zero exit code 1.; 1021)
[2022-12-13T16:30:55.025+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-13T16:30:55.054+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
