[2022-12-13T16:58:00.842+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: incident_etl.etl_incident manual__2022-12-13T16:57:51.666490+00:00 [queued]>
[2022-12-13T16:58:00.867+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: incident_etl.etl_incident manual__2022-12-13T16:57:51.666490+00:00 [queued]>
[2022-12-13T16:58:00.868+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T16:58:00.868+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-13T16:58:00.868+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T16:58:00.887+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): etl_incident> on 2022-12-13 16:57:51.666490+00:00
[2022-12-13T16:58:00.899+0000] {standard_task_runner.py:55} INFO - Started process 2289 to run task
[2022-12-13T16:58:00.903+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'incident_etl', 'etl_incident', 'manual__2022-12-13T16:57:51.666490+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_incident.py', '--cfg-path', '/tmp/tmpioeg0gs1']
[2022-12-13T16:58:00.904+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask etl_incident
[2022-12-13T16:58:00.999+0000] {task_command.py:389} INFO - Running <TaskInstance: incident_etl.etl_incident manual__2022-12-13T16:57:51.666490+00:00 [running]> on host ff6f332d28b5
[2022-12-13T16:58:01.094+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=noe
AIRFLOW_CTX_DAG_ID=incident_etl
AIRFLOW_CTX_TASK_ID=etl_incident
AIRFLOW_CTX_EXECUTION_DATE=2022-12-13T16:57:51.666490+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-13T16:57:51.666490+00:00
[2022-12-13T16:58:01.106+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-13T16:58:01.107+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl/etl_incident.py']
[2022-12-13T16:58:01.127+0000] {subprocess.py:86} INFO - Output:
[2022-12-13T16:58:03.027+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-13T16:58:03.028+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/etl/etl_incident.py", line 9, in <module>
[2022-12-13T16:58:03.028+0000] {subprocess.py:93} INFO -     storage_client = storage.Client.from_service_account_json('/root/midyear-cursor-371415-a5bbee084fb8.json')
[2022-12-13T16:58:03.029+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
[2022-12-13T16:58:03.029+0000] {subprocess.py:93} INFO -     with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
[2022-12-13T16:58:03.029+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/root/midyear-cursor-371415-a5bbee084fb8.json'
[2022-12-13T16:58:03.219+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-13T16:58:03.233+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-13T16:58:03.237+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=incident_etl, task_id=etl_incident, execution_date=20221213T165751, start_date=20221213T165800, end_date=20221213T165803
[2022-12-13T16:58:03.257+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task etl_incident (Bash command failed. The command returned a non-zero exit code 1.; 2289)
[2022-12-13T16:58:03.287+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-13T16:58:03.315+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
